name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get commit hash
        id: get-commit-hash
        run: echo "::set-output name=commit-hash::$(git rev-parse --short HEAD)"

      # You may pin to the exact commit or the version.
      # uses: boomeventsorg/aws-container-registry-action@b87a2b7a075e9f3ab0fe17e95f576c2e03f7e50c
      - name: Configure AWS ECR
        id: aws-registry
        uses: aws-actions/configure-aws-credentials@v3
        with:
          # AWS Access key ID with required access to ECR
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS Secret Access key with required access to ECR
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          # AWS region where is ECR placed
          aws-region: eu-west-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Publish image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
          IMAGE_VERSION: ${{ steps.get-commit-hash.outputs.commit-hash }}
        run: |
          docker build -t teamspeak --file ./teamspeak/Dockerfile .
          docker tag teamspeak:$IMAGE_VERSION 905418283206.dkr.ecr.eu-west-1.amazonaws.com/teamspeak:$IMAGE_VERSION
          docker push 905418283206.dkr.ecr.eu-west-1.amazonaws.com/teamspeak:$IMAGE_VERSION

